#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2026, Ansible Project
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = r"""
module: hello_info
short_description: Returns a greeting message
description:
  - A dummy module used to validate the collection docs build pipeline.
  - Returns a simple greeting that includes the provided name and the current
    collection version, confirming that module documentation is correctly
    generated and published by the CI workflows.
version_added: "1.0.0"
author:
  - Shahar Golshani (@shahargolshani)
options:
  name:
    description:
      - The name to include in the greeting message.
      - Defaults to C(World) when not specified.
    type: str
    default: World
  uppercase:
    description:
      - When V(true), the greeting message is returned in all uppercase letters.
    type: bool
    default: false
"""

EXAMPLES = r"""
- name: Say hello to the world
  sandbox.ci.hello_info:

- name: Say hello to Ansible
  sandbox.ci.hello_info:
    name: Ansible

- name: Say hello loudly
  sandbox.ci.hello_info:
    name: SCOM
    uppercase: true
  register: greeting

- name: Print the greeting
  ansible.builtin.debug:
    msg: "{{ greeting.message }}"
"""

RETURN = r"""
message:
  description: The greeting message generated by the module.
  returned: always
  type: str
  sample: "Hello, Ansible!"
name:
  description: The name that was passed to the module.
  returned: always
  type: str
  sample: "Ansible"
uppercase:
  description: Whether the message was uppercased.
  returned: always
  type: bool
  sample: false
"""

from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(
        argument_spec=dict(
            name=dict(type="str", default="World"),
            uppercase=dict(type="bool", default=False),
        ),
        supports_check_mode=True,
    )

    name = module.params["name"]
    uppercase = module.params["uppercase"]

    message = "Hello, {0}!".format(name)
    if uppercase:
        message = message.upper()

    module.exit_json(
        changed=False,
        message=message,
        name=name,
        uppercase=uppercase,
    )


if __name__ == "__main__":
    main()
